### ISSUE TITLE
errer handling

### ISSUE THREAD

**Issue by erichuang2015** [jolle/whis#1]
hello

I am  using express with this script, I wanna show results in the page, but I have 2 doubts

1. the output was formatted and it is json object, how can I render it in plain raw whois data ？
2.when no whois servers found, it will throw errers for express app, so is there any way to handle this error and output in the page.

thanks

**Comment by jolle** [comment]
Hi,

You can get the raw WHOIS output by giving `true` as the second argument to whis just like the documentation in the [README](https://github.com/jolle/whis#whisdomain-string-raw-boolean-server-string--promisewhoisdata) tells you:

```js
whis('google.com', true).then((result) => console.log(result));
```

You can use a try-catch block to catch errors like you would do in other NodeJS applications:
```js
try {
    whis('this.doesntexist').then(...);
} catch(e) {
    // handle error here
}
```
